spring:
  application:
    name: workers
  datasource:
    username: user123
    password: user123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/workers_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgresSQLDialect